[project]
name = "legal-data-process"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pyarrow>=21.0.0",
]

[project.scripts]
legal-data-process = "legal_data_process:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
